### ISSUE TITLE
Password changes result in repeated failures

### ISSUE THREAD

**Issue by michaeloa** [AdamNowotny/BuildReactor#101]
I ran into a problem with this during a password change on our servers. I basically forgot to change the password on BR, which essentially resulted in BR continuously pinging the server with the wrong credentials, with the result that the account got locked. Since it took a while to realize what was going on, the username got locked multiple times before we got this sorted out.

I would suggest that if the server gets 2 or 3 authorization refused in a row, the service should disable the view, rather than continue pinging the target service.

**Comment by AdamNowotny** [comment]
That's annoying...This is implemented - any passwordExpired event from the service should disable that service (https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/passwordExpiredHandler.js).

This is assuming that the returned http code is 401 so perhaps the CI server you're using is not doing that. I'd expect the response in case of wrong password would be the same when getting list of available services on setting page so this might be a way to check this. The check is in https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/buildEventProcessor.js#L5 where the "UnauthorisedError" is the error message returned from superagent library in case of 401 errors.

**Comment by AdamNowotny** [comment]
No followup so closing this. As described when a server returns 401 on update request, the pipeline is immediately disabled. If this it not the case I'd need more information to fix that.
