### ISSUE TITLE
Can't select all projects in service settings

### ISSUE THREAD

**Issue by okj579** [AdamNowotny/BuildReactor#104]
On the settings page for a Jenkins service, I can't check or uncheck all projects because of a click handler for accordion functionality.

![image](https://user-images.githubusercontent.com/40447/92469983-08bb2800-f1d6-11ea-85fe-6d6b2e7dd42a.png)
**Action:** Click on checkbox next to headline "Projects"
**Expected:** All projects are selected or unselected
**Actual:** The "Projects" box is minimized

**Comment by AdamNowotny** [comment]
This is fixed in 5.0.0.
