### ISSUE TITLE
Configuring the server url should be more explicit as to the expectations

### ISSUE THREAD

**Issue by rhettc** [AdamNowotny/BuildReactor#11]
My first attempt to setup the plugin with my Atlassian Bamboo On-Demand service failed because the url I specified didn't include /builds. Most tools that I integrate with Atlassian services collect the uri for the purposes of parsing out the scheme, host, port, etc. and those tools know the relevant path.

I'm not suggesting to change in your implementation, but if I had known that I needed to supply a url that would resolve to the page where all my build plans were included, it would have saved me a bit of poking around. I suspect that some users might even abandon the plugin before doing enough trial and error to figure this out. 

PS: Nice job! Impressive number of services supported too!

**Comment by AdamNowotny** [comment]
There is a message "For Bamboo OnDemand use https://[your_account].atlassian.net/builds" below the url so that should do for now. Might revisit if there are other similar cases.
