### ISSUE TITLE
Chrome Web Store removed BuildReactor

### ISSUE THREAD

**Issue by jljacoblo** [AdamNowotny/BuildReactor#110]
Chrome Web Store took down BuildReactor.
The link to Chrome Web Store does not work anymore.

Chrome application also disabled the existing BuildReactor app and cannot enable it again.

Please investigate.

**Comment by AdamNowotny** [comment]
It's just been removed by Google with no prior warning. I'm clarifying that but it will take some time and might require extra development. Related to "tabs" permission apparently...
In the mean time it's best to compile a local version from sources and use that instead of the WebStore one.

**Comment by jljacoblo** [comment]
Chrome application automatically re-enabled the BuildReactor extension today.

Should be back in Web store soon.

Thanks for the quick reply.

**Comment by AdamNowotny** [comment]
Updated the package in Chrome Webstore to latest version and removed "tabs" permission. It should show up correctly now
https://chrome.google.com/webstore/detail/buildreactor/agfdekbncfakhgofmaacjfkpbhjhpjmp
