### ISSUE TITLE
BuildReactor not working for GoCD anymore ?

### ISSUE THREAD

**Issue by Soadfan** [AdamNowotny/BuildReactor#145]
Hello,

My Build Reactor configs disappeared all of a sudden and i can't find GoCD anymore in the list of Services to chose from.

![image](https://github.com/user-attachments/assets/d0906c47-d07d-4914-8408-2abd6a497582)

Is this a new sad feature or a bug ?

Thanks in advance

**Comment by AdamNowotny** [comment]
Yes, sorry about that! Related to recent upgrade to 4.0.0. It's a complete rewrite and migrating the configs was too much work that I needed to complete before the background pages are not supported anymore in Chrome.
Please add the services again. In case of GoCD, it was just using cctray so you need to select "cctray XML" and append `/go/cctray.xml`. More info on cctray at https://cctray.org/servers/

**Comment by AdamNowotny** [comment]
I'm going to close this, let me know if the cctray integration has some issues.

**Comment by Soadfan** [comment]
Hello, so i tried with CCTray Xml option, with myGocdUrl/go/cctray.xml then it displays the list of all monitored builds, i select some but then when i save it's failing, giving this:

![image](https://github.com/user-attachments/assets/76cbf2ea-a68e-4e42-9da2-db1df48752d4)

**Comment by Soadfan** [comment]
Hello,

It doesn't work for me, i add a cctray one, with myGocdUrl/go/cctray.xml, it displays the monitored builds, but after selecting some of them, when i save it does

![image](https://github.com/user-attachments/assets/5dc7c1af-6c2a-4b6a-ae5d-4ba8794926c5)

**Comment by AdamNowotny** [comment]
I noticed that happening once in a while when pressing Save. Not related to GoCD specifically, just UI. Refreshing the page helps to sync the state and it works after that. In the latest version on GitHub this is fixed already, but hasn't been published to WebStore yet. Assuming you're having this problem with 4.0.0?

**Comment by Soadfan** [comment]
yes it's under 4.0.0, thanks for the information :)

**Comment by AdamNowotny** [comment]
Just published the latest 5.0.0. This should fix the issue and will show up when Google reviews it - few days at least

**Comment by Soadfan** [comment]
It works great, thanks ! :)
