### ISSUE TITLE
Travis CI doesn't appear to support private repos yet.

### ISSUE THREAD

**Issue by jonfen** [AdamNowotny/BuildReactor#17]
Only my public repos are listed as options.

**Comment by PeteCJohnson** [comment]
All of my repos appear in BuildReactor as "Offline (Cannot read property 'length' of undefined).

**Comment by AdamNowotny** [comment]
As a temporary workaround you can use the CCtray integration, more info at https://docs.travis-ci.com/user/cc-menu/

**Comment by AdamNowotny** [comment]
Travis-CI integration rewritten and should support private as well as private repos (including custom urls for enterprise accounts). Only had a chance to test with public repo so let me know if this works for private as expected.
https://github.com/AdamNowotny/BuildReactor/releases/tag/v1.1.0
