### ISSUE TITLE
Monitored build names are truncated

### ISSUE THREAD

**Issue by xbao** [AdamNowotny/BuildReactor#24]
Our jenkins server has many jobs. For each project, the different build types differ only in the last few words. In the dialog, these are truncated with '...'.

It would be nice to have an option to display to full name in the dialog

**Comment by AdamNowotny** [comment]
Does that also happen when number of columns in a row is set to 1? I'm assuming in the full-screen dashboard it's not a problem.

**Comment by xbao** [comment]
It does not happen with columns set to 1 (I didn't even know that was an option), and it's not a problem in full screen. 

Also, thanks heaps for BuildReactor! I've been using it everyday for a couple of years. Very, very nice.

**Comment by AdamNowotny** [comment]
Ok I'll close this issue for now. Fixing this might actually be quite complicated as if the names are not truncated then different builds might show in different sizes which would look weird in  multi-column view.
Glad you find BuildReactor useful :)
