### ISSUE TITLE
Configure extension popup size

### ISSUE THREAD

**Issue by blackbarn** [AdamNowotny/BuildReactor#28]
I have lots of jobs. I appreciate the fact I can configure the columns and whatnot, however the popup is still real small. It would be nice to be able to configure the popup size as I generally work on a large window.

**Comment by AdamNowotny** [comment]
The popup is not really meant to take a lot of space. Perhaps it would make sense to  have a separate view for it, .f.e. one that only shows failed and "in progress" builds.
It would make more sense for you to open the dashboard in full-screen mode in a separate browser window or even separate screen.
