### ISSUE TITLE
Add ability to export a reactor configuration

### ISSUE THREAD

**Issue by Blackbaud-FrankKurzawa** [AdamNowotny/BuildReactor#29]
It can take some time to fully configure a browser with the radiator that our team needs. If it was possible to export/import a BuildReactor configuration then it could easily be shared between team members, stored in version control for automated deployment to a build radiator, etc.

**Comment by AdamNowotny** [comment]
Just pushed the functionality to the repo, will go out to WebStore with the next release in a few days.

![screenshot from 2015-10-30 12 31 00](https://cloud.githubusercontent.com/assets/1185293/10837432/82b0b058-7f0d-11e5-9b3a-4823a6345e68.png)
