### ISSUE TITLE
invalid credentials cause hundreds of failed attempts per minute against server

### ISSUE THREAD

**Issue by jguice** [AdamNowotny/BuildReactor#3]
Specifically in this case it was a user running this plugin pointed to our teamcity instance.  If the login attempt fails it should not be retried like a mad password cracker ;)

Here's a sampling of the urls being tried:

Time    Error message   Instance    URL Count
07/02/13 08:31:38   Unauthorized: Failed to login user 'username' due to authentication error    host    /httpAuth/app/rest/buildTypes/id:bt21773/builds/count:1     20
07/02/13 08:30:38   Unauthorized: Failed to login user 'username' due to authentication error    host    /httpAuth/app/rest/buildTypes/id:bt21773/builds/count:1     20
07/02/13 08:29:38   Unauthorized: Failed to login user 'username' due to authentication error    host    /httpAuth/app/rest/buildTypes/id:bt21773/builds/count:1     20
07/02/13 08:28:38   Unauthorized: Failed to login user 'username' due to authentication error   host     /httpAuth/app/rest/buildTypes/id:bt21773/builds/count:1     20
07/02/13 08:27:38   Unauthorized: Failed to login user 'username' due to authentication error    host    /httpAuth/app/rest/buildTypes/id:bt21361/builds/running:any     20
07/02/13 08:26:38   Unauthorized: Failed to login user 'username' due to authentication error    host

Thanks.

**Comment by ClxS** [comment]
This appears to still be an issue? After changing my password last night, I got back this morning to a locked out account and a report from our IT that there were 150 incorrect password attempts. We used Fiddler to track it down to Chrome, which only had this extension installed.

It was pointing at a Jenkins CI server.

**Comment by AdamNowotny** [comment]
Haven't seen that myself, but also haven't been using Jenkins for a while.
If the response is 401, then this should be recognised by superagent as "UnauthorisedError" and trigger "passwordExpired" event (https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/buildEventProcessor.js#L5)
This is then picked up by https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/passwordExpiredHandler.js#L6 to disable the service.
There should be entries for all that in the console _for the background page_.
You could check console for logs, network tab for 401 responses or enable breakpoints when debugging to check if it's triggered correctly
