### ISSUE TITLE
Can't see last commit message on TeamCity 9.1.1 

### ISSUE THREAD

**Issue by lyns99** [AdamNowotny/BuildReactor#35]
Hi,

We've just upgraded our TC server to 9.1.1 and the last commit message is not being shown, even though the option "Show commit messages" is enabled in BuildReactor. Actually we have also moved the repository from sourcesafe into git

Any chance of having the option to display the date & time of the commit message?

Thanks,

lynsey

**Comment by AdamNowotny** [comment]
TeamCity output changed but the last commit changes should be displayed now. The fix doesn't include the new functionality of showing time and date, but that's a separate issue so closing this one.
