### ISSUE TITLE
Broken build count incorrect on badge

### ISSUE THREAD

**Issue by rdoh** [AdamNowotny/BuildReactor#37]
My icon looked like this: 
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/600838/10011581/fbaacce6-613f-11e5-88c5-9c12442a19c4.png)

I have two configurations. one Bamboo and one Snap-CI. The badge showed '-1' while two builds were in progress and none were failed.
![image](https://cloud.githubusercontent.com/assets/600838/10011519/d8689390-613e-11e5-9840-8212327fb462.png)
![pastedgraphic-3](https://cloud.githubusercontent.com/assets/600838/10011526/ed3520b8-613e-11e5-96e2-57bdba91db8b.png)

When one of the builds failed, the badge icon disappeared. So now I have a failing build but no badge.

**Comment by AdamNowotny** [comment]
Just pushed a fix for the badge so it doesn't go to negative numbers so at least should recover from this situation. No idea why would that happen though, was any of the builds broken before moving to "in progress"?

**Comment by rdoh** [comment]
Cheers Adam. Yes I think one of them was broken but can't be 100% sure now, sorry.
