### ISSUE TITLE
color of running build in the dark theme

### ISSUE THREAD

**Issue by oshai** [AdamNowotny/BuildReactor#40]
not sure if this is a question or an issue.
in the light theme when a build is running it is green with moving stripes. I am not sure what happens if the build failed before but I tend to think it will be red (I hope).
in the dark theme when the same build is running it shows as orange. I find it confusing, it seems like the build has some warnings. is that on purpose? is it configurable?
I attached some images below.
<img width="334" alt="screen shot 2015-10-14 at 09 21 08" src="https://cloud.githubusercontent.com/assets/2683969/10476272/d3b000c8-7254-11e5-846f-fbd356610a82.png">
<img width="229" alt="screen shot 2015-10-14 at 09 21 59" src="https://cloud.githubusercontent.com/assets/2683969/10476281/ebf7c6b6-7254-11e5-9962-de4350649c4b.png">

**Comment by AdamNowotny** [comment]
The original dark theme always had orange background for builds in progress...
You're right, it would be better to indicate better the previous status. The change is in repo, I'll push it to WebStore as well with next version.

**Comment by oshai** [comment]
thanks!
