### ISSUE TITLE
Running Grunt missing package plato and each-async

### ISSUE THREAD

**Issue by christofferholmstedt** [AdamNowotny/BuildReactor#45]
I just tried building the latest version from git but without experience with node/npm/grunt/bower I have no idea where in the installation process something went wrong. I did the following build in a Vagrant machine running Ubuntu, installed nodejs via apt-get (debian package).

When I run `grunt` I get the following errors:

```
Loading "plato.js" tasks...ERROR
>> Error: Cannot find module 'plato'
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'each-async'
Warning: Task "sass" not found. Use --force to continue.
```

It is obvious that I miss some packages but should those be installed with npm or some other package manage? download and build from source? or just some configuration update with bower?

**Comment by christofferholmstedt** [comment]
I think this is due to old nodejs and npm versions in the debian apt repositories but haven't confirmed it. I ended up building on a Windows machine instead with latest node LTS msi installer from node js website.

This issue is no longer blocking me in anyway but it might effect others so I will leave it open.

**Comment by AdamNowotny** [comment]
Thanks, I'll have a look. I'm finishing moving to webpack (on webpack branch) so this might go away soon.

**Comment by AdamNowotny** [comment]
Just merged the move to webpack. Bower is not used any more so perhaps that will work for you now?. Tested with node 6.8.0.
