### ISSUE TITLE
setup general ci connectors

### ISSUE THREAD

**Issue by jmecosta** [AdamNowotny/BuildReactor#49]
hi,

now i need to type for each project the ci address, user name and password. it would be nice we could create a general connector and apply to several projects

br,

Jorge Costa

**Comment by AdamNowotny** [comment]
Seems like it would be easier and faster to edit the configuration file directly. I'd rather keep things simple. Looking at https://github.com/AdamNowotny/BuildReactor/issues/48 perhaps the actual issue is that services need to support multiple branches?

**Comment by jmecosta** [comment]
Yep if also we can do this from the configuration file then should be ok. I
had not tough that it would be possible

**Comment by jmecosta** [comment]
actually, so that means that passwords will be save in plain text? ensure if the the best approach

**Comment by AdamNowotny** [comment]
You can go to "configuration" section in the settings and export current config (perhaps add one service first to see what fields are needed), then edit in the browser and press "save".
Yes, passwords are saved in plaintext in localStorage, so the assumption is you're not working on a shared machine...or if do you create a special account on the CI server just for BR.
