### ISSUE TITLE
Jenkins builds show as offline with "Cannot read property 'map' of undefined" as the error message

### ISSUE THREAD

**Issue by cobrabr** [AdamNowotny/BuildReactor#50]
All builds from one of my Jenkins server (running Jenkins version 1.653) show as offline, even though they are running properly. 

Hovering over the "Offline" tag in the builds in BuildReactor's Dashboard shows `Cannot read property 'map' of undefined` as the error message.

Here's a screenshot from the Dashboard:

![image](https://cloud.githubusercontent.com/assets/724969/14987954/b4970be0-111f-11e6-9a37-e73efd0fbc3a.png)

I have one other Jenkins server running an earlier version (1.573) that is working properly, and even the currently-failing one was working until a couple of weeks ago (when it was on a previous build of version 1.6).

I looked at the console and trying looking at the info provided by the Chrome Apps & Extensions Developer Tool and there were no errors; however, one thing in the debug information caught my attention: 

![image](https://cloud.githubusercontent.com/assets/724969/14987749/c107ff20-111e-11e6-88d4-2269e9ef93d5.png)

The first object in the array is my "old" Jenkins; the third one is the failing one. As you can see in the image, the `webUrl` property for the first one has the correct URL for the server, while the second one is null (the same applies to the 3 other builds shown in there). Thought it might be relevant. :smiley: 

Thanks.

**Comment by AdamNowotny** [comment]
The errors would show up in the background page (access through "extensions" in chrome). My guess is that it's somewhere around jenkinsBuild.js (changesets perhaps). Can you post response from http://server/job/Team4_QA/lastCompletedBuild/api/json ?

**Comment by cobrabr** [comment]
No errors that I can see in the background page, just similar logs to the ones shown in the Chrome App & Extensions Dev Tool.

Here's the response you requested (modified only to remove confidential/private information):
```JSON
{
  "actions":[
    {
      "causes":[
        {
          "shortDescription":"Started by an SCM change"
        }
      ]
    },
    {

    },
    {

    },
    {
      "buildsByBranchName":{
        "refs/remotes/origin/develop":{
          "buildNumber":2918,
          "buildResult":null,
          "marked":{
            "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
            "branch":[
              {
                "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
                "name":"refs/remotes/origin/develop"
              }
            ]
          },
          "revision":{
            "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
            "branch":[
              {
                "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
                "name":"refs/remotes/origin/develop"
              }
            ]
          }
        }
      },
      "lastBuiltRevision":{
        "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
        "branch":[
          {
            "SHA1":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
            "name":"refs/remotes/origin/develop"
          }
        ]
      },
      "remoteUrls":[
        "ssh://git@gitserver/home/git/r/dotnet"
      ],
      "scmName":""
    },
    {

    },
    {

    },
    {

    }
  ],
  "artifacts":[

  ],
  "building":false,
  "description":null,
  "displayName":"#2918",
  "duration":447662,
  "estimatedDuration":449949,
  "executor":null,
  "fullDisplayName":"Team4_QA #2918",
  "id":"2918",
  "keepLog":false,
  "number":2918,
  "queueId":1793,
  "result":"SUCCESS",
  "timestamp":1462390214280,
  "url":"http://server/job/Team4_QA/2918/",
  "builtOn":"",
  "changeSet":[
    {
      "affectedPaths":[
        "path/filename.ext"
      ],
      "commitId":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
      "timestamp":1462390091000,
      "author":{
        "absoluteUrl":"http://server/user/user.name",
        "fullName":"User Name"
      },
      "comment":"#106957: Fix conditional formatting was not applying in excel sheet when\nexport, because of date comparison with millisecond difference.\n",
      "date":"2016-05-04 15:28:11 -0400",
      "id":"5519a2746cb495110e2e77b4d01f00208ed4c40f",
      "msg":"#106957: Fix conditional formatting was not applying in excel sheet when",
      "paths":[
        {
          "editType":"edit",
          "file":"path/filename.ext"
        }
      ]
    }
  ],
  "culprits":[
    {
      "absoluteUrl":"http://server/user/user.name",
      "fullName":"User Name"
    }
  ]
}
```

**Comment by dhfernan** [comment]
I see the same issue. I am running on Jenkins v1.654.

**Comment by AdamNowotny** [comment]
@dhfernan do you see any errors in the background page? This is the confusing part, there should be an error somewhere, perhaps open background page and refresh?

**Comment by dhfernan** [comment]
@AdamNowotny, this is what I see. 
![capture](https://cloud.githubusercontent.com/assets/7574457/15060951/99661098-12e4-11e6-818b-a7ce4730094a.PNG)

**Comment by AdamNowotny** [comment]
@dhfernan Yes, that's just the web page, dashboard I assume. To see the logs of the part that parses the builds you'd need go to settings -> list of extensions -> there enable "develop mode" -> find BuildReactor -> click inspect "background" and check what's in the console

**Comment by AdamNowotny** [comment]
Jenkins integration rewritten in version 1.0.0
