### ISSUE TITLE
Support for Team Foundation Services / Server (TFS)

### ISSUE THREAD

**Issue by WebDucer** [AdamNowotny/BuildReactor#53]
Please add support for Team Foundation Services (Visual Studio Online) and on permise server.

**Comment by matthewskelton** [comment]
Would you be interested in a PR for this, @AdamNowotny?

**Comment by AdamNowotny** [comment]
Sure! I'm not using TFS myself but happy to give some pointers. You need a new folder in core/services with buildService.js in it and implement settings, availableBuilds functions and set this.Build to class with update method returning build state. This will be called for each build every interval.

**Comment by trevorreeves** [comment]
I would really appreciate this feature - we're just switching over from Team City and was expecting to have to write this soon. Open source for the win!

**Comment by matthewskelton** [comment]
Thanks, @AdamNowotny - we need TFS support for a couple of clients and BuildReactor is sooo much better than almost all alternatives, partly due to 'just working' in Chrome, so no .NET or JRE to install. We'll get started 😄

**Comment by AdamNowotny** [comment]
One more thing, you will need to register your service in src/core/main.js
The CI server selection should pick it up based on properties in the settings method.

**Comment by AdamNowotny** [comment]
Docs  about implementing new services at https://github.com/AdamNowotny/BuildReactor/blob/master/docs/adding-new-services.markdown
