### ISSUE TITLE
"Password expired. Service has been disabled"

### ISSUE THREAD

**Issue by mvidelgauz** [AdamNowotny/BuildReactor#61]
When I try to activate a project I get that message.
But URL, user name and password are all correct - I am using them with the active Jenkins installation

**Comment by AdamNowotny** [comment]
I assume getting list of projects to monitor on the settings page works fine, it's just when turning on the service. What happens is that 2 requests are made for each selected project:
```
http://[jenkins_server]/job/[project_id]/api/json
http://[jenkins_server]/job/[project_id]/lastCompletedBuild/api/json
```
If the response is 401 (unauthorised) for any of the calls then service will be disabled to avoid locking out account after too many retries.
Try with one project selected first and then add the rest. Also if you look at the background page console there should be an error for the call that causes 401.

**Comment by AdamNowotny** [comment]
Jenkins integration rewritten in version 1.0.0
