### ISSUE TITLE
Popup window width configuration

### ISSUE THREAD

**Issue by Richard-Payne** [AdamNowotny/BuildReactor#62]
How do do I make the popup window wider?  At the moment it is very narrow and makes the text unreadable.
![build reactor](https://cloud.githubusercontent.com/assets/6730730/23063670/a066f2fc-f503-11e6-8303-e87537716e24.png)

**Comment by AdamNowotny** [comment]
Your best best is to fork and modify min-width in https://github.com/AdamNowotny/BuildReactor/blob/master/src/popup/main.scss#L10
