### ISSUE TITLE
Can not remove Jenkins builds once it is deleted from the server

### ISSUE THREAD

**Issue by dhirendrarathod2000** [AdamNowotny/BuildReactor#64]
We delete builds from the Jenkins time to time and create a new one.
There is no way to remove the builds that are there on the Build reactor but deleted from Jenkins.

**Comment by AdamNowotny** [comment]
Yes, the existing builds might get out of sync at the moment. As a workaround you can select some other build and save, then uncheck and save again. You can also edit the configuration directly on the "configuration" tab

**Comment by AdamNowotny** [comment]
The workaround should be good enough
