### ISSUE TITLE
ERR_FILE_NOT_FOUND with Jenkins

### ISSUE THREAD

**Issue by christofferholmstedt** [AdamNowotny/BuildReactor#65]
This morning all browsers (both information radiator and my development machine) got ERR_FILE_NOT_FOUND.

Not sure what is going as chrome is supposed to open the plugin url at something similiar to chrome-extension://<hash>/src/dashboard/index.html

Has this happend to someone else lateley? It is odd that it happen for all browsers at the same time. Jenkins is still up and running as usual.

**Comment by AdamNowotny** [comment]
There was an update yesterday so probably related to that. What usually happens is that the dashboard page would close as the plugin is restarted.
I haven't seen it leaving the tab open with an error. Can you open it again from the popup or if fails still?

**Comment by blowsie** [comment]
I had this issue, I have to remove my bookmarks and recreate them

**Comment by christofferholmstedt** [comment]
@AdamNowotny @blowsie Thanks for the information. Yea, it is probably the bookmark that needs to be updated...but I didn't expect chrome and chromium to auto-update the plugin.

**Comment by AdamNowotny** [comment]
There's been plenty of changes internally between 0.12.1 and 1.0.0 and the URL routing configuration changed as well. Got so used to just opening the dashboard from the popup that I missed that these could be bookmarked. Please update the bookmarks.

**Comment by christofferholmstedt** [comment]
Yea, the plugin was working all the time but couldn't find the file because my bookmark was old. Can confirm this.

Still not sure why Chrome and chromium auto-updated the plugin but that is another question for another forum.

**Comment by AdamNowotny** [comment]
All Chrome extensions from the WebStore update automatically, that's why I'll try to publish new versions with smaller amount of changes. It does mean however that if you use dashboard, the page will be closed on update and you need to manually open it again.

**Comment by christofferholmstedt** [comment]
@AdamNowotny Thanks for the information. That is a big problem for information radiators. On boot it launches Chromium in kiosk mode and opens the dashboard URL. Of course it isn't everyday that the URL routing changes inside the plugin but still, how can I know if the plugin has been updated or not when it is completely automated?

I would expect the URL routing configuration to be changing up until the 1.0.0 release and between major future releases but didn't expect auto-update of plugins.
