### ISSUE TITLE
Dashboard order

### ISSUE THREAD

**Issue by blowsie** [AdamNowotny/BuildReactor#66]
As of very recently my builds are no longer showing in the correct order, they seem to be in alphabetical order.

I am using teamcity

**Comment by AdamNowotny** [comment]
Ordering and drag&drop fixed in 1.1.0
More info at https://github.com/AdamNowotny/BuildReactor/releases/tag/v1.1.0

**Comment by StefanSmith** [comment]
I think ordering may be broken again (in Chrome on Ubuntu). As of yesterday, I'm seeing alphabetical ordering in 1.2.0, rather than the ordering of the `<Projects>`. I'm using the CCTray XML-type monitor. Issue not occurring in Firefox. In both browsers, drag and drop isn't working.

**Comment by blowsie** [comment]
I too am seeing alphabetical order

**Comment by blowsie** [comment]
how does the drag and drop work?

**Comment by blowsie** [comment]
I see now, the build configurations do not match the defined order in team city, nor are they configurable in build reactor.

**Team City**
![image](https://user-images.githubusercontent.com/308572/51522247-cc7c5d80-1e20-11e9-89df-d41761010a2b.png)

**Build Reactor Settings**
![image](https://user-images.githubusercontent.com/308572/51522257-d69e5c00-1e20-11e9-8a14-b6d25be24a39.png)

**Build Reactor Dashboard**
![image](https://user-images.githubusercontent.com/308572/51522280-ea49c280-1e20-11e9-8fdb-b27b095eb39c.png)

So the problem here is that it does not respect the specified order of the builds in build reactor, nor is it configurable in build reactor.

**Comment by AdamNowotny** [comment]
Once you add the builds in BuildReactor you should be able to set the order by dragging items in the "monitored builds" panel in the service configuration. You could also go to 'configuration" tab and modify the configuration json to set the order correctly.

**Comment by blowsie** [comment]
> Once you add the builds in BuildReactor you should be able to set the order by dragging items in the "monitored builds" panel in the service configuration. You could also go to 'configuration" tab and modify the configuration json to set the order correctly.

Whilst it is possible for me to drag the order in the list it is not reflected on the dashboard. I tried doing it manually in the json config too.

**Comment by AdamNowotny** [comment]
Just tried to reproduce using the public http://teamcity.jetbrains.com but no luck, if you manage to replicate with one of the servers I have can access to then happy to have a look. Otherwise you might want to look at https://github.com/AdamNowotny/BuildReactor/blob/master/src/common/directives/service/service.js#L29 in the background page.
That's where grouping the builds is done, so that's where some reordering might happen but from what I observed the order within a group is maintained
