### ISSUE TITLE
Buildkite - Only show 10 builds

### ISSUE THREAD

**Issue by SydOps** [AdamNowotny/BuildReactor#67]
Create a new Buildkite dashboard, and choice to show more than 10 builds. 

But in the real dashboard, only shows 10 builds.

**Comment by AdamNowotny** [comment]
Just to make sure I understand...on the configuration page for new BuildKite service you can see all the builds but when you select more then 10 builds, only maximum of 10 shows up?

Pagination is currently not supported but up to 100 should be shown on the list. No idea why dashboard would be limited though. Is the same happening in popup?

**Comment by SydOps** [comment]
Not sure what happened, I can see more than 10 builds now.
