### ISSUE TITLE
TeamCity configuration no longer has branch input box

### ISSUE THREAD

**Issue by benjwarner** [AdamNowotny/BuildReactor#70]
Hey Adam.  Not sure if this is a regression, or if it is something going on at my end.... But since re-installing BuildReactor, there is no 'branch' configuration when adding TeamCity configuration.

Could you please advise?

(Awesome product btw)

**Comment by AdamNowotny** [comment]
You're right, it disappeared with latest release. Just pushed 1.1.1 that brings it back.

**Comment by benjwarner** [comment]
Awesome, thanks Adam.
