### ISSUE TITLE
Reviewer groups don't work if Bitbucket isn't mapped to the server root

### ISSUE THREAD

**Issue by organsnyder** [AdamNowotny/BuildReactor#71]
My company's Bitbucket installation is mapped to https://hostname/stash, rather than just https://hostname. When I try to use the reviewer groups feature, the reviewers list fails to populate. Looking at the Chrome dev console, I see a bunch of 404s to https://hostname/rest/api... . When I manually change those URLs to https://hostname/stash/rest/api..., then they work. Would it be possible to add subpath detection to the extension? Thanks!

**Comment by AdamNowotny** [comment]
You didn't mention the CI server used, do you mean Bamboo, not Bitbucket?
Assuming that's the case - does the list of available projects display correctly when using https://hostname/stash (so using https://hostname/stash/rest/api/latest/project) ?

**Comment by organsnyder** [comment]
So... I just realized that I added this to the wrong project (I was trying out a few Chrome extensions at the time)—sorry about that! Sorry for the confusion.
