### ISSUE TITLE
/ in name

### ISSUE THREAD

**Issue by ozbillwang** [AdamNowotny/BuildReactor#73]
I accidently change the name from `project-1` to `org/project-1`, I can't access its setting now. 

and return the url is `chrome-extension://xxxx/settings.html#!/new`

**Comment by AdamNowotny** [comment]
You can modify the service configuration directly at
`chrome-extension://xxxx/settings.html#!/configuration`
Does that help?

**Comment by ozbillwang** [comment]
I can click the configuration url, it goes to configuration setting. I still can click other pipelines without have "/" name.

**Comment by AdamNowotny** [comment]
Problems with "/" in project name are most likely CI server specific. Which one are you using?

**Comment by ozbillwang** [comment]
that's `CCTray generic` I am using and have problem.

**Comment by AdamNowotny** [comment]
Just reproduced the issue, as a temporary workaround you can modify the name on the "configuration" screen so it doesn't have "/"

**Comment by ozbillwang** [comment]
Got your point, chick the name, go the `configuration`, click `export`, change the name from `org/project-1` to `project-1` and save. 

Problem is fixed. Thanks.
