### ISSUE TITLE
Intermittently does not reflect broken builds

### ISSUE THREAD

**Issue by sidcool1234** [AdamNowotny/BuildReactor#74]
It fails to show broken builds on the Dashboard view even when a build is broken in Jenkins.

I tried clearing cache, cookies, log out/log in etc.

**Comment by AdamNowotny** [comment]
Is the result returned from the Jenkins API either FAILURE or UNSTABLE? The requests are visible in the background page.

**Comment by AdamNowotny** [comment]
Need more info on that. Please reopen if still broken with 2.0.0
