### ISSUE TITLE
Does not work with Jenkins multibranch pipeline

### ISSUE THREAD

**Issue by radarsh** [AdamNowotny/BuildReactor#75]
I would like to use this extension as it's one of the best out there. However, we use [Jenkins multibranch pipelines](https://jenkins.io/doc/book/pipeline/multibranch/#creating-a-multibranch-pipeline) within our team and this extension doesn't seem to understand this type of jobs.

Do you have a fix planned or this? Apologies if this is a duplicate issue.

**Comment by AdamNowotny** [comment]
Jenkins integration currently supports the 3 types specified at https://github.com/AdamNowotny/BuildReactor/blob/master/src/services/jenkins/jenkins.js#L4

Does the API report the type as "org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject"?
If not then it will be treated as Freestyle/Jenkins1.x project.

**Comment by radarsh** [comment]
@AdamNowotny it does indeed report as `org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject`. This is for the top level job. Does it output the logs anywhere, so that I can help you diagnose this further?

**Comment by AdamNowotny** [comment]
Yes, go to chrome://extensions/ and enable "Developer mode". You should then be able to open the background page and either check logs or debug the background.js file by putting breakpoint in the code.

**Comment by radarsh** [comment]
When do you intend to release a new version with this fix in it? Thanks.

**Comment by AdamNowotny** [comment]
Sorry about the delay, been away for a few weeks and only now getting back to it. There is a new [release 1.2.0](https://github.com/AdamNowotny/BuildReactor/releases/tag/v1.2.0) published for Chrome which contains this pull request. In the future I'll try to only close a ticket once it's changes are released

**Comment by radarsh** [comment]
Thanks I just got your new version and can confirm that it works 👍
