### ISSUE TITLE
Can't get it working with GoCD

### ISSUE THREAD

**Issue by claresudbery** [AdamNowotny/BuildReactor#77]
Hi
I am trying to get BuildReactor working with GoCD.
I have entered the url of the build server, and the user name and password, and clicked Save. Now what? When I click Show, nothing happens. When I click Dashboard, all I see is a blank black screen with GoCD written in yellow at the top. There is a section at the bottom of the config called "Monitored Builds" but it is empty. Is there supposed to be something listed here? I can't find any documentation to give me any guidance...
Cheers
Clare.

**Comment by AdamNowotny** [comment]
First the "Show" has to work so you can select builds to monitor. I'd expect error message to show up, anything showing up in the console of the settings page or background page?

**Comment by shwetado** [comment]
<img width="1680" alt="screen shot 2018-06-22 at 11 15 15" src="https://user-images.githubusercontent.com/5915740/41759737-9862ed7c-760d-11e8-92fd-ea433f058da2.png">

Nothing in the console as well. Trying to make it work with GoCD. 

Steps:
1) Selected GoCD
2) Added the URL

I should have gotten the show option, can't seem to find.

**Comment by SouGrati** [comment]
Hi
I've just configured buildReactor with GoCD, in my case the problem was the url, instead of inserting http://gocd_url/ you should put http://gocd_url/go.

To be sure the url is working, try access to cctray.xml file (ex: http://gocd_url/go/cctray.xml)

**Comment by AdamNowotny** [comment]
Yes, using just the cctray API is more flexible, the only drawback is that the icon used in notifications would just be a generic one.

**Comment by AdamNowotny** [comment]
Version 4.0.0 has GoCD service removed, use CCTray plugin to connect to GoCD.
