### ISSUE TITLE
Chrome badge not showing build status

### ISSUE THREAD

**Issue by sallen1** [AdamNowotny/BuildReactor#80]
On the parent icon on the toolbar, with some successful and some failing builds, the parent status icon is showing an empty grey square, rather than aggregating the different build statuses. 

Environment:

Windows 7 Enterprise 64 bit
Chrome 56.0.2924.87 (64 bit)

**Comment by sallen1** [comment]
On the parent icon on the toolbar, with some successful and some failing builds, the parent status icon is showing an empty grey square, rather than aggregating the different build statuses. 

Environment:

Windows 7 Enterprise 64 bit
Chrome 56.0.2924.87 (64 bit)

**Comment by brettswift** [comment]
+1,  however for me every build is green, and the icon is still grey.     When I click the icon it still pops up a window with all accurate builds.    It also doesn't show build status when a build is building. 

I have teamcity and travis-ci  configured. 

OSX.  
Chrome: 68.0.3440.106 (Official Build) (64-bit)

**Comment by AdamNowotny** [comment]
The badge display has been rewritten so hopefully this works now. The broken build count is shown as a number, with red badge. Yellow badge if some builds are in progress. If some builds are offline the badge is always grey.
