### ISSUE TITLE
Has anyone gotten this to actually work?

### ISSUE THREAD

**Issue by wmilton211** [AdamNowotny/BuildReactor#83]
Trying to hook it into Travis for the last week..cant find any documentation on how to activate it, how it points to Travis with creds/no creds or URLs to your GitHub account and how to troubleshoot common problems. It just doesnt seem to do anything...just looks at me...(mocking me...)

Do get this error message though (so there's that...):
UnauthorisedError: cannot GET https://api.travis-ci.org/repos (403)

**Comment by AdamNowotny** [comment]
It worked last time I used travis, this looks like the token you're entering is not correct.
Does the token work when using Curl as described at https://developer.travis-ci.com/authentication?

**Comment by AdamNowotny** [comment]
You can also get the token from https://travis-ci.org/account/preferences
The link is updated in release 2.0.0
