### ISSUE TITLE
Provide a privacy statement for BuildReactor

### ISSUE THREAD

**Issue by Juli76911** [AdamNowotny/BuildReactor#86]
Hi,
can you provide an official privacy statement for the app BuildReactor, that contains information about which data will be stored and for how long?

It would be great if you could include this statement into this repository.

Thanks,
Julian

**Comment by AdamNowotny** [comment]
The extension only stores configuration in local storage, pretty much what you can export on "Configuration" tab plus the view/notifications config flags. The only communication is to whatever CI servers you use. All resources are local and there is no server component so the only information I get is some Google WebStore stats about aggregated number of installations and such. Nothing from the running app.

So there is no privacy policy as no information is collected. Happy to accept PR if you want to include it.

**Comment by Juli76911** [comment]
Thanks!
