### ISSUE TITLE
Start Tab Rotate when starting one chrome window - but not another

### ISSUE THREAD

**Issue by kjeldlau-3shape** [AdamNowotny/BuildReactor#87]
As a user, I would like to start one chrome window, where Tab Rotate automatically starts, and another chrome window where it does not.

**Comment by AdamNowotny** [comment]
Not sure what changes using "Tab Rotate" requires as I've not used it myself. Happy to look at PRs for this.

**Comment by kjeldlau-3shape** [comment]
Sorry Adam. Wrote my story in the wrong GitHub window :-)
