### ISSUE TITLE
Feature request: Add timeout setting to notifications

### ISSUE THREAD

**Issue by thanxx** [AdamNowotny/BuildReactor#94]
Firstly, thanks for this project.
To me, the notifications disappear quite quickly, sometimes I do not catch what it is about.

Thus, it would be cool to set time (in seconds) after notifications will disappear.

**Comment by AdamNowotny** [comment]
The duration was configurable in earlier versions but the latest browser notifications API (https://developer.chrome.com/docs/extensions/reference/notifications/) does not support it as far as I know.
The closest setting is `requireInteraction` which could be useful for some notifications, but nothing about keeping them for longer.
