### ISSUE TITLE
Can't discover Jenkins jobs that are nested too deep

### ISSUE THREAD

**Issue by camjackson** [AdamNowotny/BuildReactor#95]
We're using a Jenkins plugin that auto-discovers repos under particular github organisations. So the path to a repo is: 

`Some root category` -> `My github org` -> `My github repo`

When adding my Jenkins server, I click "show", and the list on the right hand side shows the root category, with the github orgs listed under it and checkboxes against them. But there's no way to "expand" the org and show the repos under it.

**Comment by AdamNowotny** [comment]
Jenkins adapter rewritten and not finds jobs recursively - https://github.com/AdamNowotny/BuildReactor/blob/master/src/services/jenkins/jenkins.ts#L51
Works locally, webstore version still waiting for review
